---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - organizr-external-certificate.yaml
  - media-external-certificate.yaml
  - no-auth-middleware.yaml
