---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "local-media-${SECRET_DOMAIN/./-}"
spec:
  secretName: "local-media-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "local.media.${SECRET_DOMAIN}"
  dnsNames:
    - "local.media.${SECRET_DOMAIN}"
