---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "local-organizr-${SECRET_DOMAIN/./-}"
spec:
  secretName: "local-organizr-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "local.organizr.${SECRET_DOMAIN}"
  dnsNames:
    - "local.organizr.${SECRET_DOMAIN}"
