---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "organizr-${SECRET_DOMAIN/./-}"
spec:
  secretName: "organizr-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "organizr.${SECRET_DOMAIN}"
  dnsNames:
    - "organizr.${SECRET_DOMAIN}"
