---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "bazarr-${SECRET_DOMAIN/./-}"
spec:
  secretName: "bazarr-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bazarr.${SECRET_DOMAIN}"
  dnsNames:
    - "bazarr.${SECRET_DOMAIN}"
