---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "actual-${SECRET_DOMAIN/./-}"
spec:
  secretName: "actual-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "actual.${SECRET_DOMAIN}"
  dnsNames:
    - "actual.${SECRET_DOMAIN}"
