apiVersion: v1
kind: Secret
metadata:
    name: iot-wifi-credentials
type: Opaque
stringData:
    SSID: ENC[AES256_GCM,data:XApO19w+a9eT0Bw=,iv:bZld7AF/RTXVwcZ2QAbTfMWGK9uMXVjw0UYDoitkowo=,tag:3N0Q4TRxGCwOYkCD5+pUtQ==,type:str]
    PASSWORD: ENC[AES256_GCM,data:+UtkzGVnz9rzCtFEWjbm6vyLexbm1HwZDrKyJiroczs=,iv:+Nscmp1tmcWR3lStjua6+AynHTRrD2hoWIWjPvNWjB4=,tag:HtfBakkcIvTkS6phA8qbpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-12T04:08:52Z"
    mac: ENC[AES256_GCM,data:mHi1i2KDtgWqhJMNR8QSik41MjHdsxnMnXJq25YvsiVM7jOlljDgu7IGrMEBMu2GR24gpNHlVHRadRVTMret8aa+2EydyrcmosbL2ARRKhQqzNBcBfxvGGe+BLPGGFlAjzlpD8TsfEi3vbTxpLwPPJ0Eijeqz+VxVzaUFlK2+nI=,iv:aH7UTuAdeB7xGP2cddtWVTM/MKnNPRgIrcgkk3gyoHI=,tag:XDqjZy1C521LG7NlZRpjuA==,type:str]
    pgp:
        - created_at: "2022-09-12T04:08:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+W7UvxRvZN+ARAAlC20yBxWoxR0Aj76DDbJrmeg2DLttnAnHgap0RgySu5c
            RtXH8mbMSo9oPRmWPAAEHq5bOShhAxOYL339RCmyiHHTGKdG6uU2X728R4xuVG5p
            xmm0BNde5qMVvtBe6r39tehdiXalmgo+Uv9YgM4VFhGP8DuJiv5Lgm4jaADRDoz1
            EdSYQ9Xw0rZ6gcCznnpW2mokueyBZabmqMiPfw3HNhqzgNg9G/ZK7qHznRlomjMN
            buBsJ17Fd72R7/KiAaGhhPUUmwsm2ETgkS3sys9SMOYIUxXWEB6p3P19UbMF/Ukx
            7+cZRL4+LWUKtW5OGfWoyOWyWCZB2ED7rW7pYr0vTET8uzQgj1pdaDxo74I2mF92
            PvHUQCmjF1BsGia16AhSKClKSaPRktHtmawqjWUsOoxR61cDBOtC8xxea8VTfoi7
            aUQQWUeYcA58WHpvYDZtf5NDWrjjEHSrJ/y1IutyBETEVGWt70rFC/y63Vv680WN
            eYh5BxgZU37MV1LOd0uJR8ywpkWTod8bGRxxiCey9nu/VjueL5bjwcGNLwrfioyJ
            EIePJCkxUWZxuuP3Na6FSEgAMT08dN8zarQaNRLUt0F1GY41ARMIt2Tj4kNP6jX2
            yDS+FsIA5zH8A2KHGq5fR9Jezj5bdSfouUp8GGo+LOuz72+A+qz1a1Qvt7wtH8/S
            XgFsZdOeZCmif/EwnC6KVx2uGg1uoJTYOlbODu3BVcQR7OuKW50+pG/Ua/gI80Hh
            rT3AiUHcvtWYeVFMu9P7Bj/vRQMRKD8nzhPKqOsASkAkG8aCMUq4kc6lzDH068E=
            =Nf27
            -----END PGP MESSAGE-----
          fp: E27E48566E50908D8CBEF7603EA7716B87FC6A32
        - created_at: "2022-09-12T04:08:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZyA0QN6YgyARAAgnGMkTKiqcJSBPrSmUMUN2tGikVY3+uPoVO9XQxjqw+T
            ug2EOKxKRTb0DdAwKZO7Rjl94NQG53iZJdx1dinkGGQs7KvKAbUc2vVSm7N7cqOr
            KFlh4hL4V8UYI83b1oLOf2l8IuE/BdOA7JbbGXADzOCeOB2JXG7O4e7tRAkFyh9/
            wWtNjtmm7A7vj2jg6k7t9IFpgjP3ZCMJCz7Qn/s6OoZwxb2Ea2wLMtsXkrtH5cSY
            KFPHwnTJU+/fq6baziilSBhjFTHsre4wDj/GSK4X0ka1J9V0M6rSQmA9SaYdakHL
            B4t0aSzkgvl4xBPD8s12N1I+toOpBlC3hURIWgjVeqQD2F7aFH9k/odTR2HLCrb/
            WTEsQb+LDiYjv3oZD1+HUoqwXoPUJxE84OPu9obZbi6g5ofSjULQFU7ajmZ+Cldq
            zblKAJHLXI0rejN7DhBzLrBisEp1i9LsecRJUM4HRGqnMXWQkX3MWgZOWGT+GMz2
            LKhA3eY/XL8en7zJF4KIlet5aDLaEbuMnel/VAt1j84x4u1PRjc7LnHYGlGB37m+
            FmoqS2gFRwPOloOLeWgXLTjaTSJD069qZ6lwKgbYxPkTgFlCuqHViSZorYpnMVvU
            Cxti4ezEffoZdIWc57ZVkJy5QxdQmKgCWQtLCBbhohMz+hHL75jR2G+1/zZSBo/S
            XgGh1n20ZHx+lnf74EEl4rXMQOHSdF5JXuxWT0p/jL9gE8OgN2kAMp+vio+ajx2E
            wHYUkPsD1X94C0gCQjgO4P+LFWOx9OZlJ5af/pZ6IOy5IKKtlOMhJpmro5cWb+g=
            =sZ8X
            -----END PGP MESSAGE-----
          fp: CB53709A5F1B40DEBB94DA0D92B1D3B63A993BFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
