---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbhydra2
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbhydra2
      version: 10.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/nzbhydra2
      tag: 7.13.0
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "nzbhydra2.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "nzbhydra2.${SECRET_DOMAIN}"
            secretName: nzbhydra2-${SECRET_DOMAIN/./-}-tls
    podSecurityContext:
      fsGroup: ${NFS_GROUP_ID}
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        mountPath: /config
        size: 10Gi
      media:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        mountPath: /mnt/media
        volumeSpec:
          nfs:
            server: ${NFS_ADDRESS}
            path: ${NFS_MEDIA_PATH}
    env:
      TZ: "${TIMEZONE}"
      PUID: ${NFS_USER_ID}
      PGID: ${NFS_GROUP_ID}
    probes:
      liveness:
        spec:
          httpGet:
            path: /actuator/health/ping
      readiness:
        spec:
          httpGet:
            path: /actuator/health/ping
      startup:
        spec:
          httpGet:
            path: /actuator/health/ping
