---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 5.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      serviceMonitor:
        enabled: true
      limits_config:
        reject_old_samples: false
      storage:
        bucketnames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          s3: s3://minio.tools:9000/loki
          endpoint: minio.tools:9000
          secretAccessKey: "${SECRET_MINIO_SECRET_KEY}"
          accessKeyId: "${SECRET_MINIO_ACCESS_KEY}"
          s3ForcePathStyle: true
          insecure: true
        filesystem: null
    monitoring:
      selfMonitoring:
        grafanaAgent:
          installOperator: false
        enabled: false
    test:
      enabled: false
    # alerting_groups:
    #   #
    #   # SMART Failures
    #   #
    #   - name: smart-failure
    #     rules:
    #       - alert: SmartFailures
    #         expr: |
    #           sum by (hostname) (count_over_time({hostname=~".+"} |~ "(?i).*smartd.*(error|fail).*"[2m])) > 0
    #         for: 10s
    #         labels:
    #           severity: critical
    #           category: logs
    #         annotations:
    #           summary: "SMART has reported failures a drive on {{ $hostname }}"
      # #
      # # *arr applications
      # #
      # - name: arr
      #   rules:
      #     - alert: ArrDatabaseIsLocked
      #       expr: |
      #         sum by (app) (count_over_time({app=~".*arr"} |~ "(?i)database is locked"[2m])) > 0
      #       for: 10s
      #       labels:
      #         severity: critical
      #         category: logs
      #       annotations:
      #         summary: "{{$app}} is experiencing locked database issues"
