---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "lidarr-${SECRET_DOMAIN/./-}"
spec:
  secretName: "lidarr-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "lidarr.${SECRET_DOMAIN}"
  dnsNames:
    - "lidarr.${SECRET_DOMAIN}"
