---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nut
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: network-ups-tools
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.13"
        ports:
          http:
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd
        hosts:
          - host: "nut.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "nut.${SECRET_DOMAIN}"
            secretName: nut-${SECRET_DOMAIN/./-}-tls
    persistence:
      ups:
        enabled: true
        hostPath: /dev/bus/usb/002/003
        mountPath: /dev/bus/usb/002/003
    config:
      files:
        ups.conf: |
          [rack-ups]
            driver = "usbhid-ups"
            port = "auto"
            vendorid = "10AF"
            productid = "0001"
            product = "LiebertPSI"
            serial = ""
            vendor = "Emerson Network Power"
            bus = "002"
    metrics:
      enabled: true
    securityContext:
      privileged: true
    env:
      TZ: "${TIMEZONE}"
