---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nut
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: network-ups-tools
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      ups:
        enabled: true
        hostPath: /dev/bus/usb/002/003
        mountPath: /dev/bus/usb/002/003
    nodeSelector:
      feature.node.kubernetes.io/custom-rack-ups: "true"
    config:
      files:
        nut.conf: |
          MODE=netserver
        upsd.conf: |
          MAXAGE 20
          LISTEN 0.0.0.0
        ups.conf: |
          [rack-ups]
            driver = "usbhid-ups"
            port = "auto"
            vendorid = "10AF"
            productid = "0001"
            product = "LiebertPSI"
            serial = ""
            vendor = "Emerson Network Power"
            bus = "002"
        upsd.users: |
          [upsmon]
            password  = "${SECRET_NUT_PASSWORD}"
            actions = SET
            instcmds = ALL
            upsmon primary
        upsmon.conf: |
          MONITOR rack-ups@localhost:3493 1 upsmon "${SECRET_NUT_PASSWORD}" primary
          POLLFREQ 15
          POLLFREQALERT 5
          HOSTSYNC 15
    metrics:
      enabled: true
      exporter:
        env:
          port: 9199
        image:
          repository: ghcr.io/druggeri/nut_exporter
          tag: 3.1.1
    securityContext:
      privileged: true
    env:
      TZ: "${TIMEZONE}"
  postRenderers:
    - kustomize:
        patchesJson6902:
          - patch:
              - op: add
                path: /spec/endpoints/-
                value:
                  port: metrics
                  interval: 30s
                  scrapeTimeout: 10s
                  path: /ups_metrics
            target:
              kind: ServiceMonitor
              name: nut-network-ups-tools
