---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.goauthentik.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: flux-system
spec:
  interval: 30m
  timeout: 3m
  url: https://bjw-s.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: concourse-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: deliveryhero-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.deliveryhero.io/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: democratic-csi-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://democratic-csi.github.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: descheduler-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://kubernetes-sigs.github.io/descheduler
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitea-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://dl.gitea.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gocd-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://gocd.github.io/helm-chart
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hajimari-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://hajimari.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: infracloudio-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://infracloudio.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.jetstack.io/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://k8s-at-home.com/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kiali-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://kiali.org/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubereboot-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://kubereboot.github.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://metallb.github.io/metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server-charts
  namespace: flux-system
spec:
  interval: 15m
  timeout: 3m
  url: https://kubernetes-sigs.github.io/metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft-server-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.min.io/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-feature-discovery-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvidia-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://helm.ngc.nvidia.com/nvidia
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-ceph-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://charts.rook.io/release
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stakater-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://stakater.github.io/stakater-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nut
spec:
  chart:
    spec:
      chart: network-ups-tools
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 6.4.2
  interval: 5m
  values:
    config:
      files:
        ups.conf: |
          [rack-ups]
            driver = "usbhid-ups"
            port = "auto"
            vendorid = "10AF"
            productid = "0001"
            product = "LiebertPSI"
            serial = ""
            vendor = "Emerson Network Power"
            bus = "002"
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd
        enabled: true
        hosts:
        - host: nut.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        ingressClassName: traefik
        tls:
        - hosts:
          - nut.${SECRET_DOMAIN}
          secretName: nut-${SECRET_DOMAIN/./-}-tls
    metrics:
      enabled: true
    persistence:
      ups:
        enabled: true
        hostPath: /dev/bus/usb/002/003
        mountPath: /dev/bus/usb/002/003
    securityContext:
      privileged: true
    service:
      main:
        loadBalancerIP: 10.44.0.13
        ports:
          http:
            enabled: true
        type: LoadBalancer
---
apiVersion: v1
data:
  nut.conf: MODE=netserver
  ups.conf: |-
    [rack-ups]
      driver = "usbhid-ups"
      port = "auto"
      vendorid = "10AF"
      productid = "0001"
      product = "LiebertPSI"
      serial = ""
      vendor = "Emerson Network Power"
      bus = "002"
  upsd.conf: LISTEN 0.0.0.0
  upsd.users: '# Required file, empty by default'
kind: ConfigMap
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: ConfigMap
    internal.config.kubernetes.io/previousNames: nut-network-ups-tools-config
    internal.config.kubernetes.io/previousNamespaces: default
  labels:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: network-ups-tools
    app.kubernetes.io/version: v2.7.4-2479-g86a32237
    helm.sh/chart: network-ups-tools-6.4.2
    helm.toolkit.fluxcd.io/name: nut
    helm.toolkit.fluxcd.io/namespace: ""
  name: nut-network-ups-tools-config
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Service
    internal.config.kubernetes.io/previousNames: nut-network-ups-tools
    internal.config.kubernetes.io/previousNamespaces: default
  labels:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: network-ups-tools
    app.kubernetes.io/version: v2.7.4-2479-g86a32237
    helm.sh/chart: network-ups-tools-6.4.2
    helm.toolkit.fluxcd.io/name: nut
    helm.toolkit.fluxcd.io/namespace: ""
  name: nut-network-ups-tools
  namespace: default
spec:
  loadBalancerIP: 10.44.0.13
  ports:
  - name: http
    port: null
    protocol: TCP
    targetPort: http
  - name: server
    port: 3493
    protocol: TCP
    targetPort: server
  selector:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/name: network-ups-tools
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Service
    internal.config.kubernetes.io/previousNames: nut-network-ups-tools-metrics
    internal.config.kubernetes.io/previousNamespaces: default
  labels:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: network-ups-tools
    app.kubernetes.io/version: v2.7.4-2479-g86a32237
    helm.sh/chart: network-ups-tools-6.4.2
    helm.toolkit.fluxcd.io/name: nut
    helm.toolkit.fluxcd.io/namespace: ""
  name: nut-network-ups-tools-metrics
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9995
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/name: network-ups-tools
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Deployment
    internal.config.kubernetes.io/previousNames: nut-network-ups-tools
    internal.config.kubernetes.io/previousNamespaces: default
  labels:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: network-ups-tools
    app.kubernetes.io/version: v2.7.4-2479-g86a32237
    helm.sh/chart: network-ups-tools-6.4.2
    helm.toolkit.fluxcd.io/name: nut
    helm.toolkit.fluxcd.io/namespace: ""
  name: nut-network-ups-tools
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: nut
      app.kubernetes.io/name: network-ups-tools
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nut
        app.kubernetes.io/name: network-ups-tools
    spec:
      automountServiceAccountToken: true
      containers:
      - image: ghcr.io/k8s-at-home/network-ups-tools:v2.7.4-2479-g86a32237
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: <nil>
          timeoutSeconds: 1
        name: nut-network-ups-tools
        ports:
        - containerPort: null
          name: http
          protocol: TCP
        - containerPort: 3493
          name: server
          protocol: TCP
        - containerPort: 9995
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: <nil>
          timeoutSeconds: 1
        securityContext:
          privileged: true
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: <nil>
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/nut
          name: nut-config
        - mountPath: /dev/bus/usb/002/003
          name: ups
      - env:
        - name: HTTP_PORT
          value: "9995"
        - name: HTTP_PATH
          value: /metrics
        - name: RUST_LOG
          value: info
        image: hon95/prometheus-nut-exporter:1.1.1
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9995
          name: metrics
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      serviceAccountName: default
      volumes:
      - configMap:
          defaultMode: 256
          name: nut-network-ups-tools-config
          optional: true
        name: nut-config
      - hostPath:
          path: /dev/bus/usb/002/003
        name: ups
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: Ingress
    internal.config.kubernetes.io/previousNames: nut-network-ups-tools
    internal.config.kubernetes.io/previousNamespaces: default
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd
  labels:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: network-ups-tools
    app.kubernetes.io/version: v2.7.4-2479-g86a32237
    helm.sh/chart: network-ups-tools-6.4.2
    helm.toolkit.fluxcd.io/name: nut
    helm.toolkit.fluxcd.io/namespace: ""
  name: nut-network-ups-tools
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: nut.
    http:
      paths:
      - backend:
          service:
            name: nut-network-ups-tools
            port:
              number: null
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nut.
    secretName: nut--tls
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    internal.config.kubernetes.io/previousKinds: ServiceMonitor
    internal.config.kubernetes.io/previousNames: nut-network-ups-tools
    internal.config.kubernetes.io/previousNamespaces: default
  labels:
    app.kubernetes.io/instance: nut
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: network-ups-tools
    app.kubernetes.io/version: v2.7.4-2479-g86a32237
    helm.sh/chart: network-ups-tools-6.4.2
    helm.toolkit.fluxcd.io/name: nut
    helm.toolkit.fluxcd.io/namespace: ""
  name: nut-network-ups-tools
  namespace: default
spec:
  endpoints:
  - interval: 30s
    params:
      target:
      - localhost:3493
    path: /metrics
    port: metrics
    relabelings:
    - sourceLabels:
      - __param_target
      targetLabel: target
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/instance: nut
      app.kubernetes.io/name: network-ups-tools
