---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: keycloak-iframe
spec:
  headers:
    accessControlAllowOriginListRegex:
      - "^(?:\\S+\\.)?${SECRET_DOMAIN/./\\.}$"
    contentSecurityPolicy: "frame-src https://*.echozulu.games; object-src 'none'; script-src 'none';"
    customResponseHeaders:
      X-Frame-Options: "" # Remove this header, CSP frame-src will handle this
