---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  hostname: "keycloak.${SECRET_DOMAIN}"
  tlsSecret: "keycloak-${SECRET_DOMAIN/./-}-tls"
  # Doesn't work due to a CRD/controller mismatch
  # defaultIngressDisabled: true
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-host
      value: keycloak-postgresql
    - name: db-username
      secret:
        name: keycloak-database-credentials
        key: postgres-user
    - name: db-password
      secret:
        name: keycloak-postgresql
        key: postgresql-password
    - name: proxy
      value: reencrypt
