---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - keycloak.yaml
  - external-certificate.yaml
  - postgresql-helm-release.yaml
  - secrets.sops.yaml
