---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: democratic-csi
      version: 0.13.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  values:
    csiDriver:
      name: local.echozulu.k8s-host-02.iscsi-1
      installCRD: false
    storageClasses:
      - name: zfs-iscsi-bulk-csi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
    driver:
      existingConfigSecret: driver-config
      config:
        driver: zfs-generic-iscsi
    log-level: debug
