---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "harbor-${SECRET_DOMAIN/./-}"
spec:
  secretName: "harbor-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "harbor.${SECRET_DOMAIN}"
  dnsNames:
    - "harbor.${SECRET_DOMAIN}"
