---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: harbor
      version: 12.2.8
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: harbor-admin-password
      valuesKey: HARBOR_ADMIN_PASSWORD
      targetPath: harborAdminPassword
  values:
    global:
      storageClass: rook-fast-rust-block
    externalURL: https://harbor.echozulu.games
    service:
      type: Ingress
      tls:
        existingSecret: harbor-${SECRET_DOMAIN/./-}-tls
        # notaryExistingSecret:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        core: harbor.echozulu.games
        notary: notary-harbor.echozulu.games
    portal:
      updateStrategy:
        type: Recreate
    core:
      updateStrategy:
        type: Recreate
    jobservice:
      updateStrategy:
        type: Recreate
    registry:
      updateStrategy:
        type: Recreate
    chartmuseum:
      updateStrategy:
        type: Recreate
    notary:
      updateStrategy:
        type: Recreate
    trivy:
      ignoreUnfixed: true
      updateStrategy:
        type: RollingUpdate
