---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: harbor
      version: 15.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: harbor-admin-password
      valuesKey: HARBOR_ADMIN_PASSWORD
      targetPath: adminPassword
  values:
    global:
      storageClass: rook-fast-rust-block
    externalURL: https://harbor.${SECRET_DOMAIN}
    exposureType: ingress
    ingress:
      core:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hostname: harbor.${SECRET_DOMAIN}
        tls: false
        extraTls:
          - secretName: harbor-${SECRET_DOMAIN/./-}-tls
            hosts:
              - harbor.${SECRET_DOMAIN}
      notary:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hostname: notary-harbor.${SECRET_DOMAIN}
        tls: false
        extraTls:
          - secretName: notary-harbor-${SECRET_DOMAIN/./-}-tls
            hosts:
              - notary-harbor.${SECRET_DOMAIN}
    portal:
      updateStrategy:
        type: Recreate
    core:
      updateStrategy:
        type: Recreate
    jobservice:
      updateStrategy:
        type: Recreate
    registry:
      updateStrategy:
        type: Recreate
    chartmuseum:
      updateStrategy:
        type: Recreate
    notary:
      updateStrategy:
        type: Recreate
    trivy:
      ignoreUnfixed: true
      updateStrategy:
        type: RollingUpdate
