---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - harbor-external-certificate.yaml
  - notary-harbor-external-certificate.yaml
  - secrets.sops.yaml
