---
fail_fast: false
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - args:
          - --config-file
          - .github/lint/.yamllint.yaml
        id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)(
            bootstrap/remote/playbooks/proxmox_hosts/roles/opnsense_hosts/files/install\.txt
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            bootstrap/remote/playbooks/proxmox_hosts/roles/opnsense_hosts/files/install\.txt
          )
      - id: mixed-line-ending
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        exclude: |
          (?x)(
            .*/templates/.*|
            .*\.md|
            bootstrap/remote/playbooks/proxmox_hosts/roles/opnsense_hosts/files/install\.txt
          )
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
        exclude: |
          (?x)(
            .*\.md
          )
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.0.3
    hooks:
      - id: forbid-secrets
        exclude: |
          (?x)(
            tmpl/.*|
            cluster/apps/tools/minio/app-config/loki-chart\.yaml|
            cluster/core/cert-manager/secret\.yaml|
            cluster/apps/networking/cloudflare-credentials\.yaml
          )
  - repo: https://github.com/tarioch/flux-check-hook
    rev: v0.2.0
    hooks:
      - id: check-flux-helm-values
