---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gocd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://gocd.github.io/helm-chart
      chart: gocd
      version: 1.40.8
      sourceRef:
        kind: HelmRepository
        name: gocd-charts
        namespace: flux-system
      interval: 5m
  values:
    server:
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - gocd.echozulu.games
        tls:
          - secretName: gocd-${SECRET_DOMAIN/./-}-tls
            hosts:
              - gocd.echozulu.games
