apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
type: Opaque
stringData:
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:0gp90co1GEIHfmHEX2/vS7cQn2MKVUv8is2Z6YFrsNg=,iv:eqUc90GzB3o8B6YAQeLCEgzh3eiZdGVxFhCFbFsUXuU=,tag:Q3uuXusBwMHalj640IRgVg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:sucwXwfi8jXa,iv:XKkB7YY1TSRKgLnzP6QYPXT6Cx4YYpsQmPy63jnFa7c=,tag:viMZEs+DXKvlvdyxYHxH1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-09T17:50:37Z"
    mac: ENC[AES256_GCM,data:u1DkD3F/mU0wjS8Q0AqsGKwqQmp+UDm9arrW8tTu5aR0HRtQnQXlzn6w7bh3MlqsGW+YRdw2Vu4b9IGrMdgZEds+Kgnc+fLLNiiAqJp2HvER4l/WgiOAsJbVdTrGMzJRHbMsu41dLWvdpxSAf/32dhryYn3NV9QwmnZBkr1ZH5g=,iv:ABAr6+mTB2CQQxEntVEE6p+vKKh54mtPsLNkKSGNvIA=,tag:92iFKRD5dvTyYtDmZRu/Aw==,type:str]
    pgp:
        - created_at: "2021-10-09T17:50:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+W7UvxRvZN+AQ//XfhrW9Tcdj9UzqE2S8diG8syq8AfsFuXQna6bmGX6NrY
            H7I4BSgfte5ZBmdRcYqbpSzdZ/4wrnnK6o2QcuGEXIs8zBNocA1s3AHj2rqZHbko
            g2F2yrnnZj5aIj2iVEYywMeHPaCTDZjNKvcjZ8IGPWGjp9Yf6CLZ8vTF4OvjiCrr
            snnyDb2P2M9qmrtrl+1EKwPZXD0dmu7k9/+Argu/nfL3rECGv+G4xGjBrVkPltDK
            QSX2yzCON+aCDVlGxfqoNVW3WTDZnsQ+4uj2Qcyv7vHN3D1/v1ni8shmeRB8ifhD
            QEaIhF/5HVRYifN43SXXNxvtgD+GDO3VnN3nTFDpzEjPFSCVJjSoUKJvEYbGpEOm
            xqwBVsm0F8s3aO/jjuc8fUxGOYpNj54ia+GLNmIaLhnTWaLI8Ls6wFUurz82x8L0
            ckJOriTHlRBYvLmCNBPwz+yJWaNk1LHcx6D8o5K4dSkBJ7edWVYH0z3UCdo0Owlf
            05WGoDTaFBMXuorOCiP35C3pO7H+KX/AqnMAXmtQICC2xAH5/CryXRpLKOGb6KdR
            BeP5SC37L5tQgUEILYjv1Fefnk8rulVVyG/r2zQXYKU6NjQLlIE4ca/y/b8ql0gz
            OJ2fQ46z5tF8nuMO9LlCg0ar0MfqO3ScWt/B3hD3kBTri9POWlndp3N5xiZPSv/S
            XgGnsOifsJMSr7X8AiviwBgIHUJSJffcz+YIrGiyPPwGBeKIizpdLnLeiJ6uzirf
            /MHo6xZTpEOkn2hy8AFWbKpgxlg7zs9I7npS1JwH0CcYFlqWjTOf2xEnKKC6EoA=
            =I8EZ
            -----END PGP MESSAGE-----
          fp: E27E48566E50908D8CBEF7603EA7716B87FC6A32
        - created_at: "2021-10-09T17:50:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZyA0QN6YgyARAAxObqsB6pb3Qq+rp8o2x5F1sCliCmMJWNUcZ/2vGruYkR
            cYNiHQQzw/kEtJ+05ou/Zf8yiLOkycAfAQR8E1wfPh1PBfWPUsuOvZbwZ9Y9fFcI
            ZlX6a+auRV97hQkMynXZ0ZT06Ir6emHO1juk90oy3ZoeP+gVwCQrMqC2cFT6i9uv
            xK4I3Lmt5oMikDvxF8uIH0UZI5t56GRekCU5eowv+dX+pq5JOuKrXoYI1bYEpdeg
            BdyuVQ1drrO9n/jnSLTgoir52xdhGM0lV7ZptXrNXQL0o+fYI1lU2Fr7KWv1QojO
            JFoh6w7/HC6sPNZpcTmnEaigjeOqLge64yPnj7UaBjj1TCFHTLRrIaEL4mChVmAM
            nlJN1K/epzy1TtGLi34c0t8YR7ieddjv98VfliwfgU8Dj4ZX8V3tXQDcUN/KQI+g
            cEgkoYAD7+q2HctlZgbtoYS1bm+OS6tJJOUi6Q2zyzTCcrR1BzpNum9Km5DHchrz
            9rVCFtjjbn48jeU/IITSx82Jq9s7Srgnn3um/yHFGaIqiQVKQRr0QpTogrItJxwP
            SXyBg/TJ7uvx9HeEWmNZsZMoX4KSrJI6XkN1WqgxwUNVQuLz5GDMlaJy8sYZcdbM
            m7PCE4i0T10GoleHEUJpYpUrsbOgWXdEaapD5Yrg3qzwUjfANzsZjAgpIISdd5TS
            XgHU6mh9VBeHAVtUkqDgjjnPmI22IfAyOeHXMYNZq3QA97N7di3k6yTJqH0kpDIV
            bxV19dZBxW2d73G7KOVu9J29jp/bkYd2WS3Ci7LEtQfEx9F6cmo9JNLoMBneTr4=
            =cUrY
            -----END PGP MESSAGE-----
          fp: CB53709A5F1B40DEBB94DA0D92B1D3B63A993BFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
