---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 9.6.1
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: gitea-admin-credentials
  values:
    image:
      repository: gitea/gitea
      tag: 1.21.11
    gitea:
      config:
        server:
          ROOT_URL: https://gitea.${SECRET_DOMAIN}/
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: gitea.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
        - host: git.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-${SECRET_DOMAIN/./-}-tls
          hosts:
            - gitea.${SECRET_DOMAIN}
            - git.${SECRET_DOMAIN}
