---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    gitea:
      admin:
        existingSecret: gitea-admin-credentials
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: gitea.echozulu.games
          paths:
            - path: /
              pathType: Prefix
        - host: git.echozulu.games
          paths:
            - path: /
              pathType: Prefix
