apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-credentials
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:SYDm4FhiXQXJen9LyXTCf2IqJkOO7uUEDhZfdpXJm5NB+Ca4RWvB+nDYCsb3hDmcJpBiw4M3hQjpt5nhPrYiTgAC9w61YtRCZCW1qt64Tj2eenaTfGSwfXiyomP+nEr00JzTTZmM4qCqnkKkZFdaObJpdwLmZcmWVsf4V/9qZ0Er6MsFZOre6BYfewKs9aIzNpQZYwLc2QwzPf+GYG03BnVeAyLXzH+LFyf6DUeos+ImsTSbthyc8Qo6xiRC6M0mOoKa3Z9y0j6e1wOv39J/nxdJwfCFP4NemAveIH/o99zLWYqSROW8FAleTHCC,iv:IALvtuHhIZa1GXD5D03HcBuGtaPHi91zBtALmryt270=,tag:6EvxVliIanB49Oi5c2zuMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-18T00:02:05Z"
    mac: ENC[AES256_GCM,data:qO4RB8ldcEYZjNE0zttKfeFmtmUlZHbfLYP8RY/e3hZiiNeh0eo78DWYrWnho++xDyg+8IXzoTdlz+mQ+eVFj5Anh9d1CrDWwWmK4d4i3ORiZ7Ze0emDTOlKq76cO7mN9KhABiZJ8Ts+LyZFMAGUFPO/Qb7/VNPuBvE5aYBkVmQ=,iv:nlpYCtQBLzqnFLuSD5Lcs5s9ewuur6XF8BvSrn2soIs=,tag:hbxuasYkvImKUNy5DVeSCg==,type:str]
    pgp:
        - created_at: "2022-01-17T20:57:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+W7UvxRvZN+AQ//Ua6hjL6h/bS+zmts1oUExTD3ZWUUnxWvaExyT8ctWr1U
            LafV2g/fDZ7T4LC3cTtZSrAA2W/uEv0O6ZuKdxYbFOVfNeH4KeJrtVqSAkbD3n64
            Yd+lNoJXk8GT6dD2hOpQypg1womltGImIKUPVuFKm+U8Ccgc6NV7ILxkkFWhWByO
            HEcaxsq10NPttl4du496lOLTs6fS3QkqmMl0UJvVeJXGxzLgPR/ALA+cqmnKayjR
            9Ii6Pz5VBQzcu7prpL7dt/4WMMkzAqvSh+EtGXEh26A9FTftIrh8BNIqJ6zJuMZt
            NODOuO3iIvUWkW1kYDsdZ682bjWh7yJEOnapR1Gx1Skxx50t6K82TgZN3lol93eq
            +ffu8cMplBDhbibLqycKnouQ9eyIOLW393a11MmW9gstZZ/6z+YKVQtOZp4vikHP
            S3TKrOKC54X273i845G8HbkbiI7rokUOCDIbY4wSBAxq1Zh+XlVVx9hUpXlIZxAP
            j8Z4DhAfIUYfSI9x96NTGqt1WtFSBGpixDtWUngETkiLklHVaz9TrC/3joSPXpcK
            Ed8IO44IaqEk+c/Ieb6denGr+pv1akoJlK6FEBdXmfZiEVhUWv7zWI+vAV9fXVM6
            /QueHQbPnu/6rqz9AYEqB8MFOdoR96Xq602D7rGr8GUH7acdnrq/riUkshpj1gHS
            XgHgxzK9I55Se71CEjCZRClNUH1JYUdTuLquHbVJ36pmvTxHGtrvKako47qLIaF4
            C8Lmf/2Dt/yN8M/h7R1G0HGYzPxwLyz2brOHJVNTMX9B3x4vb1Ts+6jyuyDFOHg=
            =LUgX
            -----END PGP MESSAGE-----
          fp: E27E48566E50908D8CBEF7603EA7716B87FC6A32
        - created_at: "2022-01-17T20:57:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZyA0QN6YgyAQ/6A4ayA/oqREHKkPaCRwox/A5hGBUAAa+1C4/jGybD2mLR
            RKq6PEPGxGYlBmWaKV8ZD0kJ2RADn+yzBvy9tuIwbWKCj481+pctV1Ijdo6R3Iut
            LAqMxM0q/+U4ONEolvO7GTvzvMZ5vlcuYfWWIjCFvQs+mIpR/ImZpfPL29xNAvP4
            7mhrIVQE73ay2HBIyVs4PBpxoiuByzJeUyrznReYd0Kh94g9Ul06ZfBM7QxqnkA9
            MD4JVFo15uQHydbiyhOiNrDGqD+UXADiM2KCAr8AtoLaJB9qODCFg6NUPzrX1EXV
            NIpI1lvVQpn7fsCU6bKsdXFX4Ddx1Lhyr+LYAZw/QOR9MI7Yy9a0nPg1B3Ue9sZx
            0razvcyBUzrKYveojR5lqwnmRTcYxeGGDqQgq8IoHqx1oM4ybdI3YOf6TlLRZSnA
            rwedaQQkFGCH4LERRI7TGaFFmZPEdvlKsV3fSEBEpxnkG/heGH9ntY9EDpjC0KZ/
            p++Z/iJ8KhAk03EUYKjZTQvYC15yBgOjdMc+hgnnI9k2RvbMl/PKH2tF5uNlmOCb
            qtfs4QQR857aQy7MjNk2PHxzam6hhjjwOhZjFCnA/mhFVeYRXIrdDvaQIkNVtbgn
            mxnNzb/qvbxU/j7eRKpYYiQvM8PH88SGGkDwgDc+LrguvkHdMA5h2s6KBckVmNnS
            XgGVaMEF/Yulab8BaIYmhcoak4Y/jNBEQhzUsso8WS9AQ1NCoxVR5WCH7gM1e2VB
            8/HZznFH/4yfl0FbFJ6IK4d4fX+TQktgalpXB42zj/Iats4EU8n3VMd9eezTVVM=
            =f9I+
            -----END PGP MESSAGE-----
          fp: CB53709A5F1B40DEBB94DA0D92B1D3B63A993BFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
