---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "jellyfin-${SECRET_DOMAIN/./-}"
spec:
  secretName: "jellyfin-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "jellyfin.${SECRET_DOMAIN}"
  dnsNames:
    - "jellyfin.${SECRET_DOMAIN}"
