---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/jellyfin
      tag: 2021.12.16
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jellyfin.${SECRET_DOMAIN}"
            secretName: jellyfin-${SECRET_DOMAIN/./-}-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        size: 25Gi
      media:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        mountPath: /mnt/media
        volumeSpec:
          nfs:
            server: ${NFS_ADDRESS}
            path: ${NFS_MEDIA_PATH}
    nodeSelector:
      feature.node.kubernetes.io/custom-intel-gpu: "true"
    resources:
      limits:
        gpu.intel.com/i915: 1
    # Log show that Jellyfin is bugged and not pulling the JELLYFIN_CONFIG_DIR var specifically so this is a workaround
    args:
      - --configdir /config/config
    env:
      TZ: "${TIMEZONE}"
      JELLYFIN_DATA_DIR: /config/data
      JELLYFIN_CONFIG_DIR: /config/config
      JELLYFIN_LOG_DIR: /config/log
      PUID: ${NFS_USER_ID}
      PGID: ${NFS_GROUP_ID}
