---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.5.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/jellyfin
      tag: 10.8.5
    command:
      - /bin/bash
    args:
      - -c
      - >-
        ln /dev/dri/card1 /dev/dri/card0;
        ln /dev/dri/renderD129 /dev/dri/renderD128;
        /usr/bin/jellyfin --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg --webdir=/usr/share/jellyfin/web
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: media-jellyfin-redirect-auth@kubernetescrd
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jellyfin.${SECRET_DOMAIN}"
            secretName: jellyfin-${SECRET_DOMAIN/./-}-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
        size: 100Gi
      media:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        mountPath: /mnt/media
        volumeSpec:
          nfs:
            server: ${NFS_ADDRESS}
            path: ${NFS_MEDIA_PATH}
      redirect-js:
        enabled: true
        type: configMap
        name: redirect-js
        subPath: redirect.js
        mountPath: /usr/share/jellyfin/web/redirect.js
        readOnly: true

    nodeSelector:
      feature.node.kubernetes.io/custom-intel-gpu: "true"
    resources:
      limits:
        gpu.intel.com/i915: 1
    env:
      TZ: "${TIMEZONE}"
      JELLYFIN_DATA_DIR: /config/data
      JELLYFIN_CONFIG_DIR: /config/config
      JELLYFIN_LOG_DIR: /config/log
      PUID: ${NFS_USER_ID}
      PGID: ${NFS_GROUP_ID}
