---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jellyfin-redirect-auth
spec:
  redirectRegex:
    # Match a login-specific JS file and redirect it to one that redirects to the login URL
    regex: "session-login.*"
    replacement: redirect.js
