---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-configuration
data:
  http.yaml: |
    http:
      server_host: 0.0.0.0
      ip_ban_enabled: true
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        - ${CLUSTER_IP_RANGE}
