---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-configuration
data:
  http.yaml: |
    http:
      server_host: 0.0.0.0
      ip_ban_enabled: true
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        - ${CLUSTER_IP_RANGE}
  auth_header.yaml: |
    auth_header:
      username_header: X-Forwarded-User
      debug: false
    logger:
      default: info
      logs:
        custom_components.auth_header: info
  prometheus.yaml: |
    prometheus:
      namespace: home-assistant
