---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "${TIMEZONE}"
    metrics:
      enabled: true
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: home-assistant.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
          - host: ha.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: home-assistant-${SECRET_DOMAIN/./-}-tls
            hosts:
              - home-assistant.${SECRET_DOMAIN}
              - ha.${SECRET_DOMAIN}
