---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "${TIMEZONE}"
    metrics:
      enabled: true
    persistence:
      config:
        enabled: true
      ha-configuration:
        enabled: true
        type: configMap
        name: ha-configuration
        mountPath: /init_config/
        readOnly: true
    initContainers:
      load-configuration:
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - "sh"
          - "-c"
          - |
            HA_CONFIG_FILE="/config/configuration.yaml"
            if ! ([ -f "$HA_CONFIG_FILE" ] && grep -q "#START_MARKER" "$HA_CONFIG_FILE")
            then
              echo "File or markers not found, adding them"
              # If not marker not found
              echo "#START_MARKER" >> "$HA_CONFIG_FILE"
              echo "#END_MARKER" >> "$HA_CONFIG_FILE"
            fi
            # Replace the content between the markers with a HA load command
            echo "Updating config to include init_config directory..."
            sed -ni '/#START_MARKER/{p;:a;N;/#END_MARKER/!ba;s/.*\n/!include_dir_named init_config\/\n/};p' "$HA_CONFIG_FILE"
            echo "Home-Assistant config updated"
        volumeMounts:
          - name: config
            mountPath: /config/
        securityContext:
          runAsUser: 0
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: home-assistant.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
          - host: ha.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: home-assistant-${SECRET_DOMAIN/./-}-tls
            hosts:
              - home-assistant.${SECRET_DOMAIN}
              - ha.${SECRET_DOMAIN}
