---
# See https://github.com/sleighzy/k3s-traefik-forward-auth-openid-connect for setup details
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: traefik-forward-auth-oidc
      valuesKey: SECRET
      targetPath: env.SECRET
    - kind: Secret
      name: traefik-forward-auth-oidc
      valuesKey: PROVIDERS_OIDC_ISSUER_URL
      targetPath: env.PROVIDERS_OIDC_ISSUER_URL
    - kind: Secret
      name: traefik-forward-auth-oidc
      valuesKey: PROVIDERS_OIDC_CLIENT_ID
      targetPath: env.PROVIDERS_OIDC_CLIENT_ID
    - kind: Secret
      name: traefik-forward-auth-oidc
      valuesKey: PROVIDERS_OIDC_CLIENT_SECRET
      targetPath: env.PROVIDERS_OIDC_CLIENT_SECRET
  values:
    env:
      TZ: "${TIMEZONE}"
      INSECURE_COOKIE: false
      COOKIE_DOMAIN: ${SECRET_DOMAIN}
      AUTH_HOST: "auth.${SECRET_DOMAIN}"
      URL_PATH: "/_oauth"
      DEFAULT_PROVIDER: oidc
      LOG_LEVEL: info
      LOG_FORMAT: pretty
    middleware:
      enabled: true
