---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    speaker:
      enabled: false
    configInline:
      address-pools:
        - name: default
          protocol: bgp
          avoid-buggy-ips: true
          addresses:
            - "${METALLB_LB_RANGE}"
