---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.2
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    crds:
      enabled: true
    speaker:
      enabled: true
      frr:
        enabled: true
    prometheus:
      serviceAccount: kube-prometheus-stack-prometheus
      namespace: monitoring
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
