---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vanilla
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 2Gi
    minecraftServer:
      eula: "TRUE"
      difficulty: normal
      motd: "bepis"
      ops: "solidDoWant"
      pvp: true
      memory: 2G
      serviceType: LoadBalancer
      servicePort: 25565
      loadBalancerIP: 10.44.0.7
    serviceAnnotations:
      metallb.universe.tf/allow-shared-ip: "minecraft-shared-ip"
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
    extraEnv:
      TZ: ${TZ}
