---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "nzbget-${SECRET_DOMAIN/./-}"
spec:
  secretName: "nzbget-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "nzbget.${SECRET_DOMAIN}"
  dnsNames:
    - "nzbget.${SECRET_DOMAIN}"
