---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Related issue: https://github.com/keycloak/keycloak-k8s-resources/issues/4
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/main/kubernetes/kubernetes.yml
