---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  values:
    image:
      tag: v1.10.0
    routed_namespaces:
      - media
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: &not-routed-cidrs "10.0.0.0/10"
      VPN_INTERFACE: &vpn-interface wg0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_LOCAL_CIDRS: *not-routed-cidrs
      VPN_TRAFFIC_PORT: ${SECRET_VPN_SERVER_PORT}
      VXLAN_ID: 65 # Avoid a collision with the default value
    publicPorts:
      - hostname: transmission
        IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
        ports:
          - type: udp
            port: ${SECRET_GLUETUN_PUBLIC_PORT}
          - type: tcp
            port: ${SECRET_GLUETUN_PUBLIC_PORT}
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.40.0
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: *vpn-interface
          - name: FIREWALL_VPN_INPUT_PORTS
            value: "${SECRET_GLUETUN_PUBLIC_PORT}"
          - name: DOT
            value: "off"
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 30s
          # - name: HEALTH_TARGET_ADDRESS
          #   value: 1.1.1.1:443
        envFrom:
          - secretRef:
              name: vpn-gateway-config
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - protocol: UDP
                  port: ${SECRET_VPN_SERVER_PORT}
            - to:
                - ipBlock:
                    cidr: 10.0.0.0/8
          # ingress:
          #   - from:
          #       - ipBlock:
          #           cidr: 0.0.0.0/0
          #         ports:
          #           - protocol: TCP
          #             port: "${SECRET_GLUETUN_PUBLIC_PORT}"
          #           - protocol: UDP
          #             port: "${SECRET_GLUETUN_PUBLIC_PORT}"
    webhook:
      gatewayDefault: false
      gatewayLabel:
      gatewayAnnotation: setGateway
      gatewayAnnotationValue: "true"
      namespaceSelector:
        label: "vpn-routed-gateway"
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/template/spec/securityContext
                value:
                  sysctls:
                    - name: net.ipv6.conf.all.disable_ipv6
                      value: "1"
            target:
              kind: Deployment
              name: vpn-gateway-pod-gateway
