---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: fast-rust
  namespace: rook-ceph
spec:
  compressionMode: aggressive # TODO benchmark this
  failureDomain: host # Tolerate a host failure
  replicated: # Replicate on 3 hosts
    size: 3
  parameters:
    compression_algorithm: lz4
