---
apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: authentik-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.goauthentik.io
  timeout: 3m
