---
apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
  timeout: 3m
