---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: concourse-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://concourse-charts.storage.googleapis.com/
  timeout: 3m
