---
apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: deliveryhero-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.deliveryhero.io/
  timeout: 3m
