---
apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: gocd-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://gocd.github.io/helm-chart
  timeout: 3m
