---
apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: nvidia-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.ngc.nvidia.com/nvidia
  timeout: 3m
