---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - curseforge-api-key.yaml
  - helm-release.yaml
configMapGenerator:
  - name: update-modpack-script
    files:
      - script/requirements.txt
      - script/main.py
  - name: minecraftinstance
    files:
      - minecraftinstance.json
