---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - curseforge-api-key.yaml
  - helm-release.yaml
configMapGenerator:
  - name: update-modpack-script
    files:
      - script/main.py
      - script/requirements.txt
      - script/startserver.sh
  # Run reduce-minecraftinstance-size.sh first to reduce file size
  - name: minecraftinstance
    files:
      - minecraftinstance.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
