---
apiVersion: v1
kind: Service
metadata:
  name: kube-controllers-metrics-svc
  namespace: calico-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  selector:
    k8s-app: calico-kube-controllers
  ports:
    - port: 9094
      targetPort: 9094
