---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.deliveryhero.io/
      chart: node-problem-detector
      version: 2.3.13
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: v0.8.10 # See https://github.com/kubernetes/node-problem-detector/issues/692 for details
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
