---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: cloudflare-credentials
      valuesKey: CLOUDFLARE_TOKEN
      targetPath: cloudflare.apiToken
  values:
    interval: 5m
    logLevel: debug
    provider: cloudflare
    annotationFilter: "external-dns/is-public in (true)"
    # extraArgs:
      # - --cloudflare-proxied
      # - --annotation-filter=external-dns/is-public in (true)
    policy: sync
    sources:
      - ingress
    # txtPrefix: "k8s."
    domainFilters:
      - "${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
