---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "concourse-${SECRET_DOMAIN/./-}"
spec:
  secretName: "concourse-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "concourse.${SECRET_DOMAIN}"
  dnsNames:
    - "concourse.${SECRET_DOMAIN}"
