---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://concourse-charts.storage.googleapis.com/
      chart: concourse
      version: 17.1.1
      sourceRef:
        kind: HelmRepository
        name: concourse-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: concourse-values
  values:
    concourse:
      web:
        externalUrl: https://concourse.${SECRET_DOMAIN}
        encryption:
          enabled: true
        kubernetes:
          teams:
            - development
          createTeamNamespaces: false
        prometheus:
          enabled: true
          ServiceMonitor:
            enabled: true
        auth:
          mainTeam:
            localUser: concourse
          oidc:
            enabled: true
            displayName: Keycloak
            issuer: https://keycloak.${SECRET_DOMAIN}/realms/Development
            groupsKey: resource_access.concourse.roles
    persistence:
      worker:
        storageClass: rook-fast-rust-block
    web:
      ingress:
        enabled: true
        hosts:
          - concourse.${SECRET_DOMAIN}
        tls:
          - secretName: concourse-${SECRET_DOMAIN/./-}-tls
            hosts:
              - concourse.${SECRET_DOMAIN}
