---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://concourse-charts.storage.googleapis.com/
      chart: concourse
      version: 17.1.1
      sourceRef:
        kind: HelmRepository
        name: concourse-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: concourse-values
  values:
    persistence:
      worker:
        storageClass: rook-fast-rust-block
    web:
      kubernetes:
        teams:
          - development
        createTeamNamespaces: false
      ingress:
        enabled: true
        hosts:
          - concourse.${SECRET_DOMAIN}
        tls:
          - secretName: concourse-${SECRET_DOMAIN/./-}-tls
            hosts:
              - concourse.${SECRET_DOMAIN}
      prometheus:
        enabled: true
        ServiceMonitor:
          enabled: true
  postRenderers:
    - kustomize:
        patchesJson6902:
          - patch:
              - op: replace
                path: /spec/template/spec/initContainers/0/env/2/valueFrom/secretKeyRef/key
                value: postgres-password
            target:
              kind: Deployment
              name: concourse-web
