---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-web
  labels:
    app: concourse-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concourse-web
subjects:
  - apiGroup: ServiceAccount
    kind: ServiceAccount
    name: concourse-web
