---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: minio
      version: 3.5.7
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: loki-chart
  values:
    mode: standalone
    replicas: 1
    persistence:
      existingClaim: storage
      storageClass: "-"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-host-02
    resources: {}
    metrics:
      serviceMonitor:
        enabled: true
    mcImage:
      repository: minio/mc
      tag: RELEASE.2021-10-07T04-19-58Z
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      ingressClassName: "traefik"
      hosts:
        - "s3.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "s3.${SECRET_DOMAIN}"
          secretName: "s3-${SECRET_DOMAIN/./-}-tls"
    consoleIngress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      ingressClassName: "traefik"
      hosts:
        - "minio.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "minio.${SECRET_DOMAIN}"
          secretName: "minio-${SECRET_DOMAIN/./-}-tls"
    # Minio console doesn't trust cert despite x509 being placed in correct directory
    # tls:
    #   enabled: true
    #   certSecret: minio-tools-svc-cluster-local-tls
    #   publicCrt: tls.crt
    #   privateKey: tls.key
