---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://operator.min.io/
      chart: minio-operator
      version: 4.2.10
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    tenants: {}
