---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: minio
    env:
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_UPDATE: "off"
      TZ: "America/Chicago"
    envFrom:
      - secretRef:
          name: minio
    args:
      - server
      - /data
      - --console-address
      - :9001
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 9001
          api:
            enabled: true
            port: 9000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - hosts:
              - "minio.${SECRET_DOMAIN}"
            secretName: "minio-${SECRET_DOMAIN/./-}-tls"
          - hosts:
              - "s3.${SECRET_DOMAIN}"
            secretName: "s3-${SECRET_DOMAIN/./-}-tls"
    persistence:
      config:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /mnt/bulk-pool-01/minio
        mountPath: /data
    podSecurityContext:
      fsGroup: 2000
    podAnnotations:
      secret.reloader.stakater.com/reload: "minio"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
