---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  storageClassName: zfs-iscsi-bulk-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
