---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "github-flux-webhook-${SECRET_DOMAIN/./-}"
spec:
  secretName: "github-flux-webhook-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "github-flux-webhook.${SECRET_DOMAIN}"
  dnsNames:
    - "github-flux-webhook.${SECRET_DOMAIN}"
