---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-webhook
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: github-webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
    - kind: Kustomization
      name: apps
      apiVersion: v1beta1
    - kind: Kustomization
      name: core
      apiVersion: v1beta1
    - kind: Kustomization
      name: crds
      apiVersion: v1beta1
