---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: insurgency
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-host-01
    image:
      repository: ghcr.io/gameservermanagers/gameserver
      pullPolicy: IfNotPresent
      tag: ins
    persistence:
      data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
        mountPath: /data
        storageClass: zfs-iscsi-bulk-csi
      instance-config:
        enabled: true
        type: secret
        name: insurgency
        subPath: instance.cfg
        mountPath: /data/config-lgsm/insserver/instance.cfg
        readOnly: true
      server-config:
        enabled: true
        type: secret
        name: insurgency
        subPath: insserver.cfg
        mountPath: /data/serverfiles/insurgency/cfg/insserver.cfg
        readOnly: true
      metrics-config:
        enabled: true
        type: secret
        name: insurgency
        mountPath: "-"
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: insurgency
        loadBalancerIP: 10.44.0.12
        ports:
          http:
            enabled: false
          rcon:
            primary: true # Used for probes
            port: 27015
            protocol: TCP
          game:
            port: 27015
            protocol: UDP
          metrics:
            port: 9137
            protocol: HTTP
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
    sidecars:
      metrics:
        image: ghcr.io/galexrt/srcds_exporter:v1.5.1
        args:
          - --collectors.enabled
          - map,playercount,players
          - --config.file
          - /srcds.yaml
        ports:
          - containerPort: 9137
            name: metrics
        volumeMounts:
          - mountPath: /srcds.yaml
            name: metrics-config
            readOnly: true
            subPath: srcds.yaml
