---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - secrets.sops.yaml
configMapGenerator:
  - name: insurgency-entrypoint
    files:
      - entrypoint-user.sh
  - name: insurgency-motd
    files:
      - motd.txt
  - name: insurgency-mods
    files:
      - installed-mods.txt
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
