---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "calibre-server-${SECRET_DOMAIN/./-}"
spec:
  secretName: "calibre-server-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "calibre-server.${SECRET_DOMAIN}"
  dnsNames:
    - "calibre-server.${SECRET_DOMAIN}"
