---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-1
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.8.1
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 1Gi
    securityContext:
      fsGroup: ${NFS_GROUP_ID}
    minecraftServer:
      eula: "TRUE"
      difficulty: normal
      motd: "bepis"
      ops: "solidDoWant"
      pvp: true
    persistence:
      dataDir:
        enabled: true
        Size: 5Gi
