---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.44.0.0/16
  SVC_TRAEFIK_ADDR: 10.44.0.1
  ZFS_ADDRESS: 10.2.1.2
  NFS_ADDRESS: 10.2.1.2
  NFS_GROUP_ID: "2000"
  NFS_MEDIA_PATH: /mnt/bulk-pool-01/media
