---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_IP_RANGE: 10.42.0.0/16
  METALLB_LB_RANGE: 10.44.0.0/16
  SVC_TRAEFIK_ADDR: 10.44.0.1
  ZFS_ADDRESS: 10.2.1.2
  NFS_ADDRESS: 10.2.1.2
  NFS_USER_ID: "2000"
  NFS_GROUP_ID: "2000"
  NFS_MEDIA_PATH: /mnt/bulk-pool-01/media
  TIMEZONE: "America/Chicago"
  K3S_CHANNEL: "https://update.k3s.io/v1-release/channels/stable"
