---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
      interval: 5m
  values:
    worker:
      config:
        sources:
          pci:
            deviceClassWhitelist:
              - "02"
              - "0200"
              - "0207"
              - "0300"
              - "0302"
            deviceLabelFields:
              - vendor
          usb:
            deviceClassWhitelist:
              - "03"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: "amd-gpu"
              matchOn:
                - pciId:
                    class:
                      - "0300"
                    vendor:
                      - "1002"
            - name: "rack-ups"
              labels:
                ups: "rack-ups"
              matchOn:
                - usbId:
                    class: ["03"]
                    vendor: ["10af"]
                    device: ["0001"]
