---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.16.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
      interval: 5m
  values:
    worker:
      config:
        sources:
          pci:
            deviceClassWhitelist:
              - "02"
              - "0200"
              - "0207"
              - "0300"
              - "0302"
            deviceLabelFields:
              - vendor
          usb:
            deviceClassWhitelist:
              - "03"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            - name: "intel-quicksync"
              labels:
                intel.feature.node.kubernetes.io/quicksync: "true"
              matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    class:
                      op: In
                      value:
                        - "0300"
                    vendor:
                      op: In
                      value:
                        - "8086"
            - name: "rack-ups"
              labels:
                ups.feature.node.kubernetes.io/rack: "true"
              matchFeatures:
                - feature: usb.device
                  matchExpressions:
                    class:
                      op: In
                      value:
                        - "03"
                    vendor:
                      op: In
                      value:
                        - "10af"
                    device:
                      op: In
                      value:
                        - "0001"
