---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: ./manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio-source
        namespace: flux-system
      interval: 1h
  values:
    enableCRDTemplates: false
