---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: istio-operator
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: itsio-operator-chart
        namespace: flux-system
      interval: 5m
  values:
    enableCRDTemplates: false
