---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atm7-updated
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.20.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 16Gi
        cpu: 4000m
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 25
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-host-01
          - weight: 75
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-host-04
    livenessProbe:
      initialDelaySeconds: 300
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 300
      periodSeconds: 30
    minecraftServer:
      eula: "TRUE"
      difficulty: normal
      motd: "bepis"
      ops: "solidDoWant"
      pvp: true
      type: AUTO_CURSEFORGE
      autoCurseForge:
        apiKey:
          existingSecret: curseforge-api-key
          secretKey: CURSEFORGE_API_KEY
        slug: all-the-mods-7
      memory: 16G
      serviceType: LoadBalancer # Temp disable
      loadBalancerIP: 10.44.0.8
      rcon:
        enabled: true
        existingSecret: rcon-password
        serviceType: LoadBalancer
        loadBalancerIP: 10.44.0.8
    rconServiceAnnotations:
      metallb.universe.tf/allow-shared-ip: "minecraft-atm7-shared-ip"
    serviceAnnotations:
      metallb.universe.tf/allow-shared-ip: "minecraft-atm7-shared-ip"
    persistence:
      dataDir:
        enabled: true
        Size: 16Gi
    podSecurityContext:
      runAsNonRoot: false
    extraEnv:
      TZ: ${TZ}
