---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: factorio-angelbob
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: factorio
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      tag: 1.1.61
    env:
      TZ: ${TZ}
      UPDATE_MODS_ON_START: true
    # This host has the newest/fastest CPU and RAM
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-host-01
    persistence:
      config:
        enabled: true
      mod-list:
        enabled: true
        type: configMap
        name: factorio-mod-list
        subPath: mod-list.json
        mountPath: /helmconfig/mod-list.json
        readOnly: true
    initContainers:
      copy-modlist:
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - "sh"
          - "-c"
          - |
            mkdir -p /factorio/mods
            cp -vL /helmconfig/mod-settings.json /factorio/mods/mod-settings.json
        volumeMounts:
          - name: mod-list
            mountPath: /helmconfig/
          - name: config
            mountPath: /factorio/
        securityContext:
          runAsUser: 0
    config:
      factorio_server:
        save_name: ${SECRET_DOMAIN}-AngelBob
        generate_new_save: false
        update_mods_on_start: true
        load_latest_save: true
        token: ${SECRET_FACTORIO_TOKEN}
        username: ${SECRET_FACTORIO_USERNAME}
      server_settings:
        name: ${SECRET_DOMAIN}-AngelBob
        description: "Don't step on it"
        game_password: ${SECRET_FACTORIO_PASSWORD}
        non_blocking_saving: true
        afk_autokick_interval: 60
        auto_pause: true
        autosave_interval: 5
        autosave_slots: 20
        ignore_player_limit_for_returning_players: true
        visibility:
          public: true
        require_user_verification: true
        token: ${SECRET_FACTORIO_TOKEN}
        username: ${SECRET_FACTORIO_USERNAME}
        admins:
          - ${SECRET_FACTORIO_USERNAME}
      map_gen_settings:
        cliff_settings:
          cliff_elevation_interval: 0
          richness: 0
