---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: factorio-angelbob
spec:
  entryPoints:
    - factorio-angelbob
  routes:
    - services:
        - name: factorio-angelbob
          port: 34197
          weight: 0
