---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "alert-manager-${SECRET_DOMAIN/./-}"
  namespace: monitoring
spec:
  secretName: "alert-manager-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "alert-manager.${SECRET_DOMAIN}"
  dnsNames:
    - "alert-manager.${SECRET_DOMAIN}"
