---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "prometheus-${SECRET_DOMAIN/./-}"
  namespace: monitoring
spec:
  secretName: "prometheus-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "prometheus.${SECRET_DOMAIN}"
  dnsNames:
    - "prometheus.${SECRET_DOMAIN}"
