---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kiali.org/helm-charts
      chart: kiali-operator
      version: 1.50.0
      sourceRef:
        kind: HelmRepository
        name: kiali-charts
        namespace: flux-system
      interval: 5m
  values:
    onlyViewOnlyMode: true
    cr:
      create: true
      spec:
        auth:
          strategy: anonymous
        deployment:
          view_only_mode: true
          ingress:
            enabled: true
            class_name: traefik
            override_yaml:
              spec:
                rules:
                  - host: kiali.${SECRET_DOMAIN}
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: "kiali"
                              port:
                                number: 20001
                tls:
                  - hosts:
                      - kiali.${SECRET_DOMAIN}
                    secretName: "kiali-${SECRET_DOMAIN/./-}-tls"
        external_services:
          istio:
            root_namespace: istio-system
          prometheus:
            url: http://prometheus-prometheus.monitoring.svc.cluster.local:9090
          grafana:
            dashboards:
              # - name: "Istio Service Dashboard"
              #   variables:
              #     namespace: "var-namespace"
              #     service: "var-service"
              # - name: "Istio Workload Dashboard"
              #   variables:
              #     namespace: "var-namespace"
              #     workload: "var-workload"
              - name: "Istio Mesh Dashboard"
              - name: "Istio Control Plane Dashboard"
              - name: "Istio Performance Dashboard"
              - name: "Istio Wasm Extension Dashboard"
            auth:
              type: basic
              username: "admin"
              password: "password" # TODO temporary integrate with IdP after setup
            enabled: true
            in_cluster_url: http://grafana.monitoring.svc.cluster.local:80
            url: https://grafana.${SECRET_DOMAIN}
        istio_namespace: istio-system
        kiali_feature_flags:
          certificates_information_indicators:
            enabled: true
            secrets:
              - "cacerts"
              - "istio-ca-secret"
