---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "flood-${SECRET_DOMAIN/./-}"
spec:
  secretName: "flood-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "flood.${SECRET_DOMAIN}"
  dnsNames:
    - "flood.${SECRET_DOMAIN}"
