---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "flood.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "flood.${SECRET_DOMAIN}"
            secretName: flood-${SECRET_DOMAIN/./-}-tls
    persistence:
      config:
        enabled: true
        mountPath: /config
    env:
      TZ: "America/Chicago"
      FLOOD_OPTION_RUNDIR: /config
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_TRURL: "http://transmission.media.svc.cluster.local:$(TRANSMISSION_SERVICE_PORT_HTTP)/transmission/rpc/"
      FLOOD_OPTION_TRUSER:
        valueFrom:
          secretKeyRef:
            name: transmission-credentials
            key: username
      FLOOD_OPTION_TRPASS:
        valueFrom:
          secretKeyRef:
            name: transmission-credentials
            key: password
