---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "esphome-${SECRET_DOMAIN/./-}"
spec:
  secretName: "esphome-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "esphome.${SECRET_DOMAIN}"
  dnsNames:
    - "esphome.${SECRET_DOMAIN}"
