---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: factorio-vanilla
spec:
  entryPoints:
    - factorio-v
  routes:
    - services:
        - name: factorio-vanilla
          port: 34197
          weight: 0
