apiVersion: v1
kind: Secret
metadata:
    name: transmission-credentials
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:tpoe1QLkfqcaHFfjHg689Q==,iv:NjK9dxeoDUQe82JADSNmbQuGN2UwYJkxoe9tHgPPrG0=,tag:X+WykjjTSIZUdoTc4zqPyQ==,type:str]
    password: ENC[AES256_GCM,data:lbKWI6OqJbeDgC7mGOQqWg==,iv:r6Y37EWu7GI/mRkgkTQGi78pZcnzsN0+90U+CtzsBFo=,tag:vlRMkWt4/SezeFiMRVrT5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-08T19:37:21Z"
    mac: ENC[AES256_GCM,data:Iqi64GRRUPQpsNkSDC+9uvbe2m+lssW2kkw1vga8IX8qNtiieJvoiYCGR4c+jk2cOtMjkiUcgkqkXRNBUmshv5oj3pu2cJy0WYyV+s1F5dtmt7WBpVcveKBLS3nC2rgSwKdQdT5u3JDd1cBGEod8Fb2LbfT66eiwjnQjCt7NJII=,iv:r46nNg7CUOxe9vtwraurqgw+a9TLSUuxTwYEu5Lq0tc=,tag:rMqBm/aLcFirUf2Io2y7QA==,type:str]
    pgp:
        - created_at: "2021-10-08T19:37:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+W7UvxRvZN+AQ/9Em5gNF7TNuExiMuPcpdCOJ8yAcGyvZLgshhIFmIBtbzW
            QPiOBO2zo5d0sYPUY449Q4wH8lHUzvLwJC75VN8edaN6KMP/5Ge1i2FLbIBbIRWC
            qz4UZlBw+VsxFlLqA1aEhKtB5E165W2RuZJfVe+8dTpm3hmV/ez1ZVKJYEygQTfL
            Ahhc2UVeP8tewofilWBw7Ucdi05uZYHgTC0pZ1iA+aw0VVJNzZlofEa0eqTbkNSZ
            F2U65FUM+aP0LUxhpxGZmS1oOjWcEfuoKDlFzx6PNZXlnmjpoDGmOfMY1FwxdAOj
            bmxvblAq+ODfnPlUAezajxTYCPvcD/fIAdShg0vEWecMrsdhz9V8z6ihI9vXnHp4
            S6cVv38rvBgeiTn5+b6gp3Guc8kPblhlanlgrrmeW2I6N4Px53NjB206oQy+dQgo
            vjO6hLuMZJDFviy8SD5Z3L/+i8O7/f3q975pK07DOGe3omTMxLEGFTPx/g0+hdof
            G0LdXKWSc07++GWs6oXYAl+S84KwY0oMz66elr95lSaWenb696n8jqt+F+JblFWK
            jJ9r2UZTNu2yKEmGaVcp4aF75Ram+BrE8QwC92zjPyfe+7DWP73d+b6XVVrVPgVc
            6PIi/081cwfBf/4cYUBL59PBLLsZgiyy1uizZlXIZJiMSI7UtbCkO6bmFypibMHS
            XgHeDpGbxCwR9TCp+k1IiItLVVPF8BsYMsv3Xqo9Xj2p9hNldjDpb5BoWFE7JCLb
            H50lHFYWOyp+GXtW/LrsXo8BXoDtiSlEzrN6bu4izFxBPcxa7AHFSAiGcsvnEyg=
            =Cnu3
            -----END PGP MESSAGE-----
          fp: E27E48566E50908D8CBEF7603EA7716B87FC6A32
        - created_at: "2021-10-08T19:37:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxZyA0QN6YgyAQ//UFamSZKF5csZu4s/JH4R038f+ymg7xKrA6ZMM1RsFdWG
            qX58SoLS+5jR95d9OyR7n0fFrq4wjpvyHlZSdYn82YxSErxLaAxcfWFwM7jvRa1C
            6SPC6FchNJIr7qtl9fqAG04QdhfMjUr+1G9xUnClspcQFO0mZhKpboAhhELHd61k
            DsTB5n5kXzrr2IdlPBvUJC+Z3CS8hV4zkYe2esiRVODGRxKhSN5Zr7AW72bgv2ea
            8W7IniXhuGAPXXSMIaPwMXOvxd/ouXP2SAF5nJI/NybBmhx7wwg/KXkk+gZCT525
            96i+M1dyfwY01n1NB1LeOcdgSGSaV2/H8bm7GxkYSHl79LyZspMvqpk7xjUfasTc
            9dAv16i2tMjAOQk/cFIrJmClCE7SJhXvMg4X9FQLe2YEA2taczAnIAl4ZEnFaZ/p
            oNm3UJ/V63+iKpAxkCMSTY14XBldA+YcqWx1xUzrx1N8Mo4N6qroQ4RX9AhkqLF+
            L3QKSo3ofRk2ixi60OluIo+O4v2rqeYQQj5htOI/zXwsB0aTYD7zl+EOOAVtQTvu
            mzyY2g7hToHjpJAuEjc1Xb73IJh6OD0FjIwcJuRADyF+Hxc1PzW9+hz1l8rCNFz4
            R40V1LJN7Q+5P1cuzdMGldnXtT4fakO3L53KcuUgTeZTFs8hp56miBkynB73nMTS
            XgFgpK2Ev21m4nGmi9stcbRI8rDPpxP+pLEDsm6Dp6ZptwobDeApcn8JxzPN8aRS
            K6hVrWdqSSR7gwmUtXir0MojealaRb7yvxvijsP4FlQgmyB/jm/bM1p/K7RL8lw=
            =c9gV
            -----END PGP MESSAGE-----
          fp: CB53709A5F1B40DEBB94DA0D92B1D3B63A993BFB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
