---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: transmission
      version: 8.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd
        hosts:
          - host: "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "transmission.${SECRET_DOMAIN}"
            secretName: transmission-${SECRET_DOMAIN/./-}-tls
    additionalContainers:
      exporter:
        name: exporter
        image: "metalmatze/transmission-exporter:master"
        env:
          - name: WEB_ADDR
            value: ":9100"
          - name: TRANSMISSION_USERNAME
            valueFrom:
              secretKeyRef:
                name: transmission-credentials
                key: username
          - name: TRANSMISSION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: transmission-credentials
                key: password
        ports:
          - name: metrics
            containerPort: 9100
    service:
      metrics:
        enabled: true
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9100
    persistence:
      config:
        enabled: true
        mountPath: /config
      media:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        mountPath: /mnt/media
        volumeSpec:
          nfs:
            server: ${NFS_ADDRESS}
            path: ${NFS_MEDIA_PATH}
    env:
      TZ: "${TIMEZONE}"
      TRANSMISSION_DOWNLOAD_DIR: /mnt/media/transmission/downloads
      TRANSMISSION_INCOMPLETE_DIR: /mnt/media/transmission/incomplete
      TRANSMISSION_WATCH_DIR: /mnt/media/transmission/watch
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
      TRANSMISSION_WATCH_DIR_ENABLED: true
      TRANSMISSION_DOWNLOAD_QUEUE_ENABLED: false
      TRANSMISSION_WATCH_FORCE_GENERIC: true
      TRANSMISSION_PEER_PORT: ${SECRET_GLUETUN_PUBLIC_PORT}
      TRANSMISSION_RPC_USERNAME:
        valueFrom:
          secretKeyRef:
            name: transmission-credentials
            key: username
      TRANSMISSION_RPC_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: transmission-credentials
            key: password
    podSecurityContext:
      fsGroup: ${NFS_GROUP_ID}
      sysctls:
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
    securityContext:
      runAsUser: ${NFS_USER_ID}
      runAsGroup: ${NFS_GROUP_ID}
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.41.0
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL_VPN_INPUT_PORTS
            value: "${SECRET_GLUETUN_PUBLIC_PORT}"
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 30s
          - name: FIREWALL_INPUT_PORTS
            value: 9091
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: 10.0.0.0/10
        envFrom:
          - secretRef:
              name: gluetun-config
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - protocol: UDP
                  port: ${SECRET_VPN_SERVER_PORT}
            - to:
                - ipBlock:
                    cidr: 10.0.0.0/8
