---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transmission-metrics
  labels:
    app.kubernetes.io/name: transmission
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
