---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "jackett-${SECRET_DOMAIN/./-}"
spec:
  secretName: "jackett-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "jackett.${SECRET_DOMAIN}"
  dnsNames:
    - "jackett.${SECRET_DOMAIN}"
