---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jackett
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      jackett:
        containers:
          jackett:
            image:
              repository: linuxserver/jackett
              tag: 0.22.1468
            env:
              PUID: 1000
              PGID: 1000
              TZ: "${TIMEZONE}"
            probes:
              liveness: &probe
                type: AUTO
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
    persistence:
      config:
        enabled: true
        size: 1Gi
        accessMode: ReadWriteOnce
    service:
      jackett:
        controller: jackett
        ports:
          http:
            port: 9117
    ingress:
      jackett:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd
        hosts:
          - host: "jackett.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: jackett
        tls:
          - hosts:
              - "jackett.${SECRET_DOMAIN}"
            secretName: jackett-${SECRET_DOMAIN/./-}-tls
