---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      timeZone: "America/Chicago"
      startTime: "2am"
      endTime: "5am"
      rebootCommand: "/usr/local/sbin/fast-reboot"  # kexec reboot
      drainGracePeriod: 120
    metrics:
      create: true
