---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubereboot.github.io/charts/
      chart: kured
      version: 5.6.1
      sourceRef:
        kind: HelmRepository
        name: kubereboot-charts
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      timeZone: "${TIMEZONE}"
      startTime: "2am"
      endTime: "5am"
      rebootCommand: "/usr/local/sbin/fast-reboot"  # kexec reboot
      drainGracePeriod: 120
    metrics:
      create: true
