---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "vaultwarden-${SECRET_DOMAIN/./-}"
spec:
  secretName: "vaultwarden-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "vaultwarden.${SECRET_DOMAIN}"
  dnsNames:
    - "vaultwarden.${SECRET_DOMAIN}"
