---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: games-on-whales
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: games-on-whales
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    runtimeClassName: nvidia
    persistence:
      home:
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
      nvidia-drv:
        enabled: true
        type: hostPath
        hostPathType: File
        readOnly: true
        mountPath: /nvidia/xorg/nvidia_drv.so
        hostPath: /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so
      libglxserver-nvidia:
        enabled: true
        type: hostPath
        hostPathType: File
        readOnly: true
        mountPath: /nvidia/xorg/libglxserver_nvidia.so
        hostPath: /usr/lib/x86_64-linux-gnu/nvidia/xorg/libglxserver_nvidia.so
    # graphic_resources:
    #   nvidia.com/gpu: 1
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.5"
        annotations:
          metallb.universe.tf/allow-shared-ip: GOW
      udp:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.5"
        annotations:
          metallb.universe.tf/allow-shared-ip: GOW
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: gow.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: gow-${SECRET_DOMAIN/./-}-tls
            hosts:
              - gow.${SECRET_DOMAIN}
    xorg:
      refreshrate: 60
      resolution: 1920x1080
    firefox:
      enabled: false
    steam:
      enabled: false
  patches:
    - patch: |-
        $patch: merge
        spec:
          template:
            spec:
              containers:
                - name: xorg
                  volumeMounts:
                    - name: libglxserver-nvidia
                      readOnly: true
                      mountPath: /nvidia/xorg/libglxserver_nvidia.so
                    - name: nvidia-drv
                      readOnly: true
                      mountPath: /nvidia/xorg/nvidia_drv.so
      target:
        kind: Deployment
        name: games-on-whales
