---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: games-on-whales
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: games-on-whales
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    runtimeClassName: nvidia
    persistence:
      home:
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
      nvidia-xorg-config:
        enabled: true
        type: configMap
        name: nvidia-xorg-config
        mountPath: "-"
      multimc:
        enabled: true
        mountPath: "-"
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
      nvidia-drv:
        enabled: true
        type: hostPath
        hostPathType: File
        readOnly: true
        mountPath: /nvidia/xorg/nvidia_drv.so
        hostPath: /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so
      libglxserver-nvidia:
        enabled: true
        type: hostPath
        hostPathType: File
        readOnly: true
        mountPath: /nvidia/xorg/libglxserver_nvidia.so
        hostPath: /usr/lib/x86_64-linux-gnu/nvidia/xorg/libglxserver_nvidia.so
    # graphic_resources:
    #   nvidia.com/gpu: 1
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.5"
        annotations:
          metallb.universe.tf/allow-shared-ip: GOW
      udp:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.5"
        annotations:
          metallb.universe.tf/allow-shared-ip: GOW
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: gow.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: gow-${SECRET_DOMAIN/./-}-tls
            hosts:
              - gow.${SECRET_DOMAIN}
    xorg:
      refreshrate: 60
      resolution: 1920x1080
      display: :99
    retroarch:
      enabled: false
    firefox:
      enabled: false
    steam:
      enabled: false
    initContainers:
      mkhomemultimcdirs:
        image: busybox:1.36.1
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - chown -R 1000:1000 /home/multimc
        volumeMounts:
          - name: multimc
            mountPath: /home/multimc
    additionalContainers:
      multimc:
        image: gitea.${SECRET_DOMAIN}/fheinecke/gow-multimc:latest
        imagePullPolicy: Always
        workingDir: /workdir
        env:
          - name: DISPLAY
            value: :99
        volumeMounts:
          - name: dev-input
            mountPath: /dev/input
            readOnly: true
          - name: udev
            mountPath: /run/udev
            readOnly: true
          - name: xorg
            mountPath: /tmp/.X11-unix
          - name: dshm
            mountPath: /dev/shm
          - name: multimc
            mountPath: /home/multimc
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: v1
              kind: Deployment
              metadata:
                name: games-on-whales
              spec:
                template:
                  spec:
                    containers:
                      - name: xorg
                        volumeMounts:
                          - name: libglxserver-nvidia
                            readOnly: true
                            mountPath: /nvidia/xorg/libglxserver_nvidia.so
                          - name: nvidia-drv
                            readOnly: true
                            mountPath: /nvidia/xorg/nvidia_drv.so
                          - name: nvidia-xorg-config
                            readOnly: true
                            mountPath: /usr/share/X11/xorg.conf.d/09-nvidia-custom-location.conf
                            subPath: 09-nvidia-custom-location.conf
            target:
              kind: Deployment
              name: games-on-whales
