---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: games-on-whales
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: games-on-whales
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      home:
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
    graphic_resources:
      gpu.intel.com/i915: 1
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.5"
        annotations:
          metallb.universe.tf/allow-shared-ip: GOW
      udp:
        type: LoadBalancer
        loadBalancerIP: "10.44.0.5"
        annotations:
          metallb.universe.tf/allow-shared-ip: GOW
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: gow.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: gow-${SECRET_DOMAIN/./-}-tls
            hosts:
              - gow.${SECRET_DOMAIN}
