---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-xorg-config
data:
  09-nvidia-custom-location.conf: |
    # Look for the nvidia_drv.so module in a custom location, to make it easier for
    # people to map the host's driver version as a bind volume. If there is no
    # driver in that location, this is a no-op.
    Section "OutputClass"
        Identifier "nvidia"
        MatchDriver "nvidia-drm"
        Driver "nvidia"
        Option "AllowEmptyInitialConfiguration"
        ModulePath "/nvidia/xorg"
        Option "PrimaryGPU" "yes"
    EndSection
