---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "calibre-${SECRET_DOMAIN/./-}"
spec:
  secretName: "calibre-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "calibre.${SECRET_DOMAIN}"
  dnsNames:
    - "calibre.${SECRET_DOMAIN}"
