---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi-poller
      version: 10.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: unifi-credentials
      valuesKey: UP_UNIFI_DEFAULT_USER
      targetPath: env.UP_UNIFI_DEFAULT_USER
    - kind: Secret
      name: unifi-credentials
      valuesKey: UNIFI_POLLER_PASS
      targetPath: env.UP_UNIFI_DEFAULT_PASS
  values:
    env:
      TZ: "${TIMEZONE}"
      UP_UNIFI_DEFAULT_ROLE: unifi-controller"
      UP_UNIFI_DEFAULT_URL: "https://${UNIFI_CONTROLLER_ADDRESS}:8443"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
