---
apiVersion: v1
kind: Secret
metadata:
  name: loki-chart
type: Opaque
stringData:
  values.yaml: |
    users:
      - accessKey: ${SECRET_MINIO_ACCESS_KEY}
        secretKey: ${SECRET_MINIO_SECRET_KEY}
        policy: readwrite
    buckets:
      - name: loki
