---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "rcon-${SECRET_DOMAIN/./-}"
spec:
  secretName: "rcon-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "rcon.${SECRET_DOMAIN}"
  dnsNames:
    - "rcon.${SECRET_DOMAIN}"
