---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "flaresolverr-${SECRET_DOMAIN/./-}"
spec:
  secretName: "flaresolverr-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "flaresolverr.${SECRET_DOMAIN}"
  dnsNames:
    - "flaresolverr.${SECRET_DOMAIN}"
