---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Provider
metadata:
  name: github
spec:
  type: github
  address: https://github.com/solidDoWant/infra-mk2
  secretRef:
    name: github-notifications-apitoken
