#!/usr/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

kexec -l --reuse-cmdline --initrd={{ initrd_path }} {{ vmlinuz_path }}
sync
umount -a
kexec -e
