---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: private-base
  namespace: flux-system
spec:
  interval: 30m
  url: https://gitea.${SECRET_DOMAIN}/cluster/private-bridge.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # except for the base directory
    !/cluster/private-base
