---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "readarr-${SECRET_DOMAIN/./-}"
spec:
  secretName: "readarr-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "readarr.${SECRET_DOMAIN}"
  dnsNames:
    - "readarr.${SECRET_DOMAIN}"
