---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: istio-operator
    meta.helm.sh/release-namespace: istio-operator
