---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - metallb-system.yaml
  - networking.yaml
  - rook-ceph.yaml
  - monitoring.yaml
  - tools.yaml
  - democratic-csi.yaml
  - games.yaml
  - media.yaml
  - development.yaml
  - istio-operator.yaml
  - istio-system.yaml
  - keycloak.yaml
